# Generated by Django 3.1.7 on 2021-03-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('num_page', models.IntegerField()),
                ('genre', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('type1', models.CharField(choices=[('BULLET', 'bullet'), ('FOOD', 'food'), ('TRAVEL', 'travel'), ('SPORT', 'sport')], default='SPORT', max_length=200)),
                ('publisher', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
